<?php
$params = $this->params;
if (!count($params)) {
    return;
}
/** @var $param \WidRestApiDocumentator\ParamInterface */
$esc = $this->plugin('EscapeHtml');
?>
<div class="api-params">
    <h5><?php echo $esc($this->header) ?></h5>
    <table class="table table-bordered">
        <tr>
            <th class="span2">Name</th>
            <th class="span1">Type</th>
            <!--<th class="span2">Value</th> -->
            <th>Description</th>
        </tr>
        <?php foreach($params as $param): ?>
            <tr class="<?php echo $param->isRequired() ? 'warning' : '' ?>">
                <td><?php echo $esc($param->getName()) ?></td>
                <td><?php echo $esc($param->getType()) ?></td>
                <!--<td><?php echo sprintf('<input name="%s[%s]" class="api-param-value" value="%s"/>', $this->namespace, $esc($param->getName()), $esc($param->getValue())); ?></td> -->
                <td><span class="label label-important"><?php echo $param->isRequired() ? 'required' : '' ?></span> <?php echo $esc($param->getDescription()) ?></td>
            </tr>
        <?php endforeach; ?>
    </table>
</div>
