<?php
/** @var $data \WidRestApiDocumentator\DataInterface */
$data = $this->data;
$config = $data->getConfig();
$resourceSet = $data->getResourceSet();
/** @var $resource \WidRestApiDocumentator\ResourceInterface */
/** @var $param \WidRestApiDocumentator\ParamInterface */
$esc = $this->plugin('EscapeHtml');
?>
<h1><?php echo $esc($config->getName()) ?> <span class="label label-info"><?php echo $esc($config->getVersion())?></span></h1>
<?php if ($this->showBackLink): ?>
<p><a href="<?php echo $this->url('rest-api-docs') ?>"><i class="icon-chevron-left"></i> Go back to list</a></p>
<?php endif; ?>

<?php foreach ($resourceSet as $number => $resource): ?>
<?php
    $description = $resource->getDescription();
    $hasDescription = !empty($description);

    $urlParams = $resource->getUrlParams();
    $queryParams = $resource->getQueryParams();
    $hasParams = count($urlParams) || count($queryParams);

    $body = $resource->getBody();
    $hasBody = count($body->getParams());

    $headers = $resource->getHeaders();
    $hasHeaders = count($headers);

    $hasOptions = $hasParams || $hasHeaders || $hasBody;
    $baseUrl = $config->getBaseUrl();
?>
<div class="api-entrypoint">
    <div class="row">
        <div class="span1">
            <span class="api-method api-method-<?php echo strtolower($esc($resource->getMethod())) ?>" ><?php echo $esc($resource->getMethod())?></span>
<!--
            <span class="api-request-action"
                  title="Run endpoint"
                  data-api-url="<?php echo $this->url('rest-api/api/post', array('id' => $this->id, 'endpoint' => $number)) ?>">
                <small>Run &raquo</small>
            </span>
-->
        </div>
        <div class="span11 api-info">
            <span class="api-url"><?php echo $esc($resource->getUrl());?></span>
            <?php if ($hasDescription): ?>
                <p class="api-description muted"><small><?php echo $esc($resource->getDescription()); ?></small></p>
            <?php endif ?>
        </div>
    </div>
    <div class="row api-entrypoint-documentation">
        <div class="span12">
            <div class="tabbable tabs-left">
                <ul class="nav nav-tabs">
                    <?php if ($hasOptions) :?>
                    <li><a href="#params-<?php echo $number?>" data-toggle="tab">Options</a></li>
                    <?php endif ?>

                    <li class="<?php echo $hasParams ? '': 'active'?>"><a href="#response-<?php echo $number?>" data-toggle="tab">Example</a></li>
                </ul>
                <div class="tab-content">

                    <?php if ($hasOptions) :?>
                    <div class="tab-pane" id="params-<?php echo $number?>">
                        <?php if ($hasHeaders) :?>
                            <?php echo $this->partial('wid-rest-api-documentator/partials/headers', array('headers' => $headers, 'namespace' => 'headers')); ?>
                        <?php endif ?>

                        <?php if ($hasParams) :?>
                        <?php echo $this->partial('wid-rest-api-documentator/partials/params', array('params' => $urlParams,   'namespace' => 'urlParams', 'header' => 'Url params')); ?>
                        <?php echo $this->partial('wid-rest-api-documentator/partials/params', array('params' => $queryParams, 'namespace' => 'queryParams', 'header' => 'Query params')); ?>
                        <?php endif ?>

                        <?php if ($hasBody) :?>
                            <?php echo $this->partial('wid-rest-api-documentator/partials/params', array('params' => $body->getParams(), 'namespace' => 'body', 'header' => 'Body')); ?>
                        <?php endif ?>
                    </div>
                    <?php endif ?>

                    <div class="tab-pane active" id="response-<?php echo $number?>">
                        <div class="tabbable">
                            <ul class="nav nav-tabs">
                                <li><a href="#api-request-uri-<?php echo $number?>" data-toggle="tab">Request URI</a></li>
                                <li><a href="#api-request-header-<?php echo $number?>" data-toggle="tab">Request headers</a></li>
                                <li><a href="#api-request-body-<?php echo $number?>" data-toggle="tab">Request body</a></li>
                                <li><a href="#api-response-header-<?php echo $number?>" data-toggle="tab">Response headers</a></li>
                                <li><a href="#api-response-body-<?php echo $number?>" class="active" data-toggle="tab">Response body</a></li>
                            </ul>
                            <div class="tab-content">
                                <pre id="api-request-uri-<?php echo $number?>"     class="tab-pane api-response api-response-requestUri">
<?php echo $baseUrl . $resource->getRequestUri(); ?>
</pre>
                                <pre id="api-request-header-<?php echo $number?>"  class="tab-pane api-response api-response-requestHeaders">
<?php if (count($resource->getRequestHeaders())) : foreach ($resource->getRequestHeaders() as $header=>$value) : ?>
<?php echo is_numeric($header) ? $value : "$header: $value"; ?>

<?php endforeach;  endif; ?>
</pre>
                                <pre id="api-request-body-<?php echo $number?>"    class="tab-pane api-response api-response-requestBody">
<?php echo $resource->getRequestBody(); ?>
</pre>
                                <pre id="api-response-header-<?php echo $number?>" class="tab-pane api-response api-response-responseHeaders">
<?php if (count($resource->getResponseHeaders())) : foreach ($resource->getResponseHeaders() as $header=>$value) : ?>
<?php echo is_numeric($header) ? $value : "$header: $value"; ?>

<?php endforeach; endif; ?>
</pre>
                                <pre id="api-response-body-<?php echo $number?>"   class="tab-pane active api-response api-response-responseBody">
<?php echo $resource->getResponseBody(); ?>
</pre>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php endforeach; ?>
